"""init

Revision ID: 7f3dc97632ef
Revises: 1d101b91841a
Create Date: 2019-09-19 19:53:29.016851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3dc97632ef'
down_revision = '1d101b91841a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=15), nullable=True))
    # ### end Alembic commands ###
