"""init

Revision ID: defcde683d78
Revises: 1d101b91841a
Create Date: 2019-09-16 17:15:17.835146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defcde683d78'
down_revision = '1d101b91841a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=15), nullable=True))
    # ### end Alembic commands ###
